# Configure Dependabot scanning.
version: 2

updates:
    # Check for updates to GitHub Actions.
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
      labels:
          - 'GitHub Actions'
          - '[Type] Build Tooling'
      ignore:
          - dependency-name: 'actions/setup-java'
            versions: ['*']
          - dependency-name: 'gradle/*'
            versions: ['*']
          - dependency-name: 'reactivecircus/*'
            versions: ['*']
          - dependency-name: 'ruby/setup-ruby'
            versions: ['*']
      groups:
          github-actions:
              patterns:
                  - '*'
